### PR TITLE
Initial packaging

### PR DESCRIPTION
**Pull request by jonathansick**
This PR sets up the packaging, test, and documentation infrastructure for the `sphinx-example-index` project. This lays the ground to port the extension itself, originally presented in astropy/sphinx-astropy#29.

The packaging started from Astropy [package-template](https://github.com/astropy/package-template), though I needed to modify the packaging to work for a Sphinx extension since infrastructure in `astropy` and `sphinx-astropy` isn't available.

- Adapted the tox configuration to test over a matrix of Sphinx versions and Python versions.
- I went ahead and migrated from Travis CI to GitHub actions. There's a regular push-based CI workflow (`.github/workflows/ci.yaml`) that does the full matrix-based testing. There's also a weekly cron-based CI that tests the extension against the master branch of Sphinx.
- I adapted the documentation set up to work independently of `sphinx-astropy`, though we still use the default Astropy theme.
- I added a development guide to outline the tox commands and other development details.

One thing I'm wondering about is whether there's a good case to continue packaging the tests inside the extensions code (i.e. the `sphinx_example_index/tests` directory layout). Is this pattern a holdover from Astropy-specific infrastructure for running tests? I think I'd be more comfortable with moving the tests out of the package.

### CODE REVIEW

**Comment by jonathansick** [comment]
I'm not seeing GitHub Actions run specifically on this PR. Maybe it's because no workflows have been merged yet, so GitHub Actions doesn't run new actions from a fork's PR? It would be useful to understand this. Anyways, this is what the GitHub Actions run looks like on my fork: https://github.com/jonathansick/sphinx-example-index/actions/runs/66014029

**Comment by bsipocz** [comment]
Yes, I believe the config files should already exist on the base branch you open the pr for. You don't see it on your fork presumably as you test the branch there rather than a pull request (and that's a different API trigger, push rather than a pr)

**Review by adrn — COMMENTED** [review]
I think this looks good! I don't have strong opinions about the test matrix, so if anyone else does have opinions there, please comment.

**Review by adrn — APPROVED** [review]
IMO: The packaging configuration can be tweaked later, but this sets up a good baseline upon which Jonathan can start building in the actual code for the extension. So I am in favor of merging this fast and requesting changes to the test matrix or package layout via further pull requests :)

**Comment by bsipocz** [comment]
We need a good test matrix, and docs, and tests by the point of the first release. Given it's not yet released, I'm OK with any plans you prefer to go ahead.

**Review by bsipocz — APPROVED** [review]

**Comment by adrn** [comment]
So be it 😄

**Pull request merged**
